---

name: Pytest Workflow

'on':
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Create output directories
        run: mkdir -p allure-results

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy history from previous runs
        if: always()
        continue-on-error: true
        run: |
          if [ -d "gh-pages/history" ]; then
            echo "Copying history from gh-pages/history"
            cp -r gh-pages/history allure-results/history
            ls -la allure-results/history
          elif [ -d "gh-pages/allure-history/history" ]; then
            echo "Copying history from gh-pages/allure-history/history"
            cp -r gh-pages/allure-history/history allure-results/history
            ls -la allure-results/history
          else
            echo "No previous history found"
          fi

      - name: Run pytest with Allure
        run: |
          pytest -s \
            --alluredir=allure-results \
            tests/

      - name: Allure Report action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          keep_files: true
