---
name: Pytest Allure Report

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Allure
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre
          URL="https://github.com/allure-framework/allure2"
          URL="$URL/releases/download/2.27.0/allure-2.27.0.tgz"
          curl -Lo allure.tgz "$URL"
          sudo tar -xzf allure.tgz -C /opt/
          sudo ln -sf /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Get previous history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages-history

      - name: Run tests with history
        run: |
          mkdir -p allure-results
          if [ -d "gh-pages-history/history" ]; then
            echo "Copying history from previous run"
            cp -r gh-pages-history/history allure-results/
          fi
          pytest --alluredir=allure-results -v

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o _site
          touch _site/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          keep_files: true
          force_orphan: false

      - name: Verify deployment
        run: |
          echo "Allure Report deployed"
          echo "URL: https://kovalillia.github.io/petstore-api-tests/"
