name: Pytest Workflow

on:
  push:
    branches:
      - master   # твоя головна гілка
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version (наприклад: 3.9 або 3.10)'
        required: true
        default: '3.9'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest pytest-html pytest-xdist

      - name: Run pytest
        run: |
          mkdir -p output/test_result output/allure/allure-results output/reports
          pytest -s --alluredir=output/allure/allure-results \
                 --junitxml=output/test_result/results.xml \
                 --html=output/reports/report.html tests/

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: output/reports/report.html
