name: Pytest Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create output directories
        run: |
          # Створюємо лише allure-results
          mkdir -p output/allure-results

      - name: Run pytest with Allure
        run: |
          # Використовуємо коректний шлях для allure-results
          pytest -s \
            --alluredir=output/allure-results \
            tests/


      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: output/allure-results


      - name: Build and deploy Allure Report to GitHub Pages
        uses: allure-framework/allure-action/upload-pages-build@v1
        id: allure-build
        with:
          artifact-path: allure-results
          base-url: ${{ github.event.repository.name }}


      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        if: always()
        with:
          artifact_name: ${{ steps.allure-build.outputs.artifact-name }}
