name: Pytest Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Установка всіх залежностей, включаючи pytest, allure-pytest, etc.
          pip install -r requirements.txt

      - name: Create output directories

        run: |
          mkdir -p output/allure/allure-results
          mkdir -p output/reports

      - name: Run pytest with Allure
        run: |
          # Запуск тестів. Переконайтеся, що 'tests/' - це правильний шлях!
          pytest -s \
            --alluredir=output/allure/allure-results \
            --junitxml=output/reports/results.xml \
            --html=output/reports/report.html \
            tests/

      - name: Add environment info to Allure
        run: |
          # Папка вже створена на кроці вище
          echo "Build Number=${{ github.run_number }}" > output/allure/allure-results/environment.properties
          echo "Build ID=${{ github.run_id }}" >> output/allure/allure-results/environment.properties
          echo "Workflow=${{ github.workflow }}" >> output/allure/allure-results/environment.properties
          echo "Branch=${{ github.ref_name }}" >> output/allure/allure-results/environment.properties
          echo "Date=$(date '+%Y-%m-%d %H:%M:%S')" >> output/allure/allure-results/environment.properties

      - name: Cache Allure history
        uses: actions/cache@v3
        with:
          path: output/allure/history
          key: allure-history-${{ github.ref_name }}
          restore-keys: |
            allure-history-

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: output/allure/allure-results
          allure_report: output/allure/allure-report
          allure_history: output/allure/history

      - name: Deploy reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: output/allure/allure-report
          keep_files: true
